name: easy_wallet
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  big_decimal: '>0.0.0'

dev_dependencies:
  http: ^0.13.4
  lints: ^1.0.0
  test: ^1.20.1
  web3dart: ^2.3.3
