name: easy_wallet
description: An easy crypto wallet magement tool
version: 1.0.0

#flutter:
#  uses-material-design: true

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  http: ^0.13.4
  big_decimal: '>0.0.0'
  dart_web3: ^0.0.3
  window_size:
    git:
      url: git://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
      ref: 89c350f787e1d7bff12b3517e5671146211ee70e
  flutter:
    sdk: flutter
  yaru: ^0.0.6


dev_dependencies:
  flutter_test: 
    sdk: flutter
    version: ^0.0.0
  lints: ^1.0.0
  mockito: ^5.1.0
  test:
